### ISSUE TITLE
IE11 mitigation not recognized after february 13 patchday

### ISSUE THREAD

**Issue by ECJ70** [vrdse/MeltdownSpectreReport#5]
Requires check for KB4074736 (IE11 security patch) and KB4074598 (Security Monthly Quality Rollup) to recognize IE11 mitigation.

https://support.microsoft.com/en-us/help/4074736/cumulative-security-update-for-internet-explorer

https://support.microsoft.com/en-us/help/4074598/windows-7-update-kb4074598

Best regards

**Comment by vrdse** [comment]
thanks, I'll fix that soon. feel free to open a PR tough. :)
